# Generated by Django 2.2 on 2021-01-25 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_operations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatbotrequest',
            name='airtime_balance',
        ),
        migrations.RemoveField(
            model_name='chatbotrequest',
            name='airtime_description',
        ),
        migrations.RemoveField(
            model_name='chatbotrequest',
            name='airtime_response_code',
        ),
        migrations.RemoveField(
            model_name='chatbotrequest',
            name='airtime_transaction_code',
        ),
        migrations.AlterField(
            model_name='chatbotrequest',
            name='lang',
            field=models.CharField(default='FR', max_length=12),
        ),
    ]
