# Generated by Django 2.2 on 2021-01-26 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_operations', '0002_auto_20210126_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotrequest',
            name='day',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='chatbotrequest',
            name='hour',
            field=models.CharField(default='', max_length=50),
        ),
    ]
