# Generated by Django 2.2 on 2021-01-29 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_operations', '0003_auto_20210126_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotrequest',
            name='department',
            field=models.CharField(default='', max_length=50),
        ),
    ]
