# Generated by Django 2.2 on 2021-01-30 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_operations', '0006_chatbotrequest_msisdn'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotrequest',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
